/**
 * Copyright 2024 Brad Anderson
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author Brad Anderson <BradA1878@pm.me>
 * @repository https://github.com/BradA1878/model-exchange-framework
 * @documentation https://brada1878.github.io/model-exchange-framework/
 */

/**
 * Events related to control loop operations
 */
export const ControlLoopEvents = {
    INITIALIZE: 'controlLoop:initialize', // Request to initialize a control loop
    INITIALIZED: 'controlLoop:initialized', // Control loop has been initialized
    STARTED: 'controlLoop:started', // Control loop has been started
    OBSERVATION: 'controlLoop:observation', // Observation submitted to control loop
    REASONING: 'controlLoop:reasoning', // Reasoning generated by control loop
    PLAN: 'controlLoop:plan', // Plan created by control loop
    EXECUTION: 'controlLoop:execution', // Plan execution started
    REFLECTION: 'controlLoop:reflection', // Reflection on execution results
    ACTION: 'controlLoop:action', // Action executed by control loop
    STOPPED: 'controlLoop:stopped', // Control loop has been stopped
    ERROR: 'controlLoop:error', // Control loop encountered an error
    
    // System LLM Integration Events
    SYSTEM_LLM_REASONING: 'controlLoop:systemLlm:reasoning', // Request System LLM reasoning
    SYSTEM_LLM_REASONING_COMPLETED: 'controlLoop:systemLlm:reasoning:completed', // System LLM reasoning completed
    SYSTEM_LLM_REASONING_FAILED: 'controlLoop:systemLlm:reasoning:failed', // System LLM reasoning failed
};

/**
 * Payload types for Control Loop events
 */
export interface ControlLoopPayloads {
    'controlLoop:initialize': { loopId: string, timestamp: number };
    'controlLoop:initialized': { loopId: string, timestamp: number };
    'controlLoop:started': { loopId: string, timestamp: number };
    'controlLoop:observation': { loopId: string, timestamp: number, observation: any };
    'controlLoop:reasoning': { loopId: string, timestamp: number, reasoning: any };
    'controlLoop:plan': { loopId: string, timestamp: number, plan: any };
    'controlLoop:execution': { loopId: string, timestamp: number, executionId: string };
    'controlLoop:reflection': { loopId: string, timestamp: number, reflection: any };
    'controlLoop:action': { loopId: string, timestamp: number, action: any, result?: any };
    'controlLoop:stopped': { loopId: string, timestamp: number, reason?: string };
    'controlLoop:error': { loopId: string, timestamp: number, error: string, context?: any };
    'controlLoop:systemLlm:reasoning': { loopId: string, timestamp: number, prompt: string };
    'controlLoop:systemLlm:reasoning:completed': { loopId: string, timestamp: number, response: any };
    'controlLoop:systemLlm:reasoning:failed': { loopId: string, timestamp: number, error: string };
}
