/**
 * Copyright 2024 Brad Anderson
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author Brad Anderson <BradA1878@pm.me>
 * @repository https://github.com/BradA1878/model-exchange-framework
 * @documentation https://brada1878.github.io/model-exchange-framework/
 */

/**
 * SystemEvents.ts
 * 
 * Event definitions for system-generated ephemeral events that provide
 * contextual intelligence and coordination hints during ORPAR transitions.
 * These events enhance agent coordination without polluting message history.
 */

import { AgentId, ChannelId } from '../../types/ChannelContext';

/**
 * System ephemeral event constants
 * These events are generated by SystemLlmService for intelligent coordination
 */
export const SystemEvents = {
    // Core ephemeral events
    EPHEMERAL_INJECTION: 'system:ephemeral:injection',
    CONTEXT_ANALYSIS: 'system:context:analysis',
    COORDINATION_HINT: 'system:coordination:hint',
    ACTIVITY_ALERT: 'system:activity:alert',
    INTERPRETATION: 'system:interpretation', // SystemLLM interpretation of agent responses
    
    // Temporal context events
    TEMPORAL_CONTEXT_UPDATE: 'system:temporal:context:update',
    TEMPORAL_PATTERN_DETECTED: 'system:temporal:pattern:detected',
    
    // ORPAR phase-specific events
    PRE_REASONING_HINT: 'system:orpar:pre:reasoning:hint',
    POST_ACTION_ANALYSIS: 'system:orpar:post:action:analysis',
    COORDINATION_OPPORTUNITY: 'system:coordination:opportunity',
    PATTERN_RECOGNITION: 'system:pattern:recognition',
    
    // System maintenance events
    MAINTENANCE_MODE: 'system:maintenance:mode'
} as const;

/**
 * Temporal context information leveraging existing Time MCP server
 * Provides time-aware intelligence for system events
 */
export interface TemporalContext {
    /** Current timestamp from Time server */
    currentTime: string;
    /** Agent's local time if timezone known */
    localTime: string;
    /** Human-readable relative time */
    relativeTime: string;
    /** Whether current time is within business hours */
    workingHours: boolean;
    /** Detected or configured timezone */
    timeZone: string;
    /** Day of week for pattern analysis */
    dayOfWeek: string;
    /** Contextual timing description */
    contextualTiming: string;
    /** Additional temporal metadata */
    metadata: {
        /** Unix timestamp for calculations */
        timestamp: number;
        /** Business hours definition */
        businessHours: {
            start: string;
            end: string;
        };
        /** Timezone offset from UTC */
        utcOffset: number;
        /** Whether it's a weekend */
        isWeekend: boolean;
    };
}

/**
 * System ephemeral event data structure
 * Contains all information needed for intelligent context injection
 */
export interface SystemEphemeralEventData {
    /** Type of ephemeral injection */
    injectionType: 'coordination_hint' | 'context_reminder' | 'activity_alert' | 'tool_suggestion' | 'pattern_insight';
    
    /** Trigger that caused this event */
    trigger: 'pre_reasoning' | 'post_action' | 'high_activity' | 'conflict_detected' | 'pattern_recognized' | 'temporal_shift';
    
    /** Main content of the ephemeral event */
    content: string;
    
    /** Rich temporal context via existing Time MCP server */
    temporalContext: TemporalContext;
    
    /** Event metadata for routing and relevance */
    metadata: {
        /** Confidence score for this event (0-1) */
        confidence: number;
        /** Relevance score for current context (0-1) */
        relevance: number;
        /** Channel activity level (0-10) */
        channelActivity: number;
        /** Specific target agents (if any) */
        targetAgents?: AgentId[];
        /** Related memory entries */
        relatedMemory?: string[];
        /** Time-based relevance scoring */
        temporalRelevance: number;
        /** When this hint becomes stale */
        expirationTime?: string;
        /** Source of the intelligence */
        source: 'system_analysis' | 'pattern_recognition' | 'coordination_analysis' | 'temporal_analysis';
        /** Related tools that might be relevant */
        suggestedTools?: string[];
        /** ORPAR phase this event relates to */
        orparPhase?: 'observation' | 'reasoning' | 'planning' | 'action' | 'reflection';
    };
    
    /** Event visibility scope */
    visibility: 'channel_only' | 'agent_specific' | 'system_wide';
    
    /** Time-to-live in milliseconds */
    ttl: number;
    
    /** Priority level for event processing */
    priority: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
}

/**
 * Channel coordination analysis result
 * Used to determine coordination opportunities
 */
export interface CoordinationAnalysis {
    /** Channel identifier */
    channelId: ChannelId;
    
    /** Active agents in channel */
    activeAgents: AgentId[];
    
    /** Detected coordination opportunities */
    opportunities: {
        /** Type of coordination opportunity */
        type: 'collaboration' | 'conflict_resolution' | 'resource_sharing' | 'knowledge_exchange';
        /** Agents involved in opportunity */
        involvedAgents: AgentId[];
        /** Opportunity description */
        description: string;
        /** Confidence score */
        confidence: number;
        /** Suggested action */
        suggestedAction: string;
    }[];
    
    /** Channel activity metrics */
    activityMetrics: {
        /** Message count in last period */
        messageCount: number;
        /** Tool usage frequency */
        toolUsage: number;
        /** Agent interaction density */
        interactionDensity: number;
        /** Time period for metrics */
        timePeriod: string;
    };
    
    /** Temporal patterns detected */
    temporalPatterns: {
        /** Pattern type */
        type: 'peak_activity' | 'collaboration_spike' | 'tool_usage_surge' | 'coordination_pattern';
        /** Pattern description */
        description: string;
        /** Temporal context */
        temporalContext: TemporalContext;
        /** Confidence in pattern */
        confidence: number;
    }[];
    
    /** Analysis timestamp */
    analysisTime: string;
}

/**
 * System event payload types for EventBus integration
 */
export interface SystemEphemeralEventPayload {
    /** Event type */
    eventType: keyof typeof SystemEvents;
    /** Event data */
    eventData: SystemEphemeralEventData;
    /** Channel context */
    channelId: ChannelId;
    /** Agent context (optional) */
    agentId?: AgentId;
    /** Event timestamp */
    timestamp: string;
    /** Unique event identifier */
    eventId: string;
}

/**
 * System coordination event payload
 */
export interface SystemCoordinationEventPayload {
    /** Event type */
    eventType: keyof typeof SystemEvents;
    /** Coordination analysis */
    coordinationAnalysis: CoordinationAnalysis;
    /** Recommended actions */
    recommendedActions: string[];
    /** Priority level */
    priority: number;
    /** Channel context */
    channelId: ChannelId;
    /** Event timestamp */
    timestamp: string;
    /** Unique event identifier */
    eventId: string;
}

/**
 * System temporal pattern event payload
 */
export interface SystemTemporalPatternEventPayload {
    /** Event type */
    eventType: keyof typeof SystemEvents;
    /** Detected pattern */
    pattern: {
        /** Pattern type */
        type: string;
        /** Pattern description */
        description: string;
        /** Temporal context */
        temporalContext: TemporalContext;
        /** Pattern confidence */
        confidence: number;
        /** Affected channels */
        affectedChannels: ChannelId[];
        /** Suggested responses */
        suggestedResponses: string[];
    };
    /** Event timestamp */
    timestamp: string;
    /** Unique event identifier */
    eventId: string;
}

// Export event types for use in other modules
export type SystemEventType = keyof typeof SystemEvents;
export type SystemEventPayload = SystemEphemeralEventPayload | SystemCoordinationEventPayload | SystemTemporalPatternEventPayload;
