// MXF Theme inspired by the OpenRouter design
export const mxfTheme = {
    dark: true,
    colors: {
        // Main colors based on the OpenRouter design 
        background: '#0f0f0f',
        surface: '#1a1a1a',
        'surface-bright': '#2a2a2a',
        'surface-light': '#3a3a3a',
        'surface-variant': '#424242',
        'on-surface-variant': '#bdbdbd',
        primary: '#6366f1',
        'primary-darken-1': '#4f46e5',
        secondary: '#7c3aed',
        'secondary-darken-1': '#6d28d9',
        error: '#f87171',
        info: '#06b6d4',
        success: '#10b981',
        warning: '#f59e0b',
        // Text colors
        'on-background': '#e5e5e5',
        'on-surface': '#e5e5e5',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-info': '#ffffff',
        'on-success': '#ffffff',
        'on-warning': '#000000',
        // Additional colors for dashboard elements
        'card-bg': '#1e1e1e',
        'sidebar-bg': '#111111',
        'nav-bg': '#151515',
    },
    variables: {
        'border-color': '#424242',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'idle-opacity': 0.04,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'activated-opacity': 0.12,
        'pressed-opacity': 0.12,
        'dragged-opacity': 0.08,
        'kbd-background-color': '#212529',
        'kbd-color': '#ffffff',
        'code-background-color': '#2d2d2d',
    },
};
