<template>
  <div class="communication-view">
    <div class="view-header">
      <h2>💬 Communications</h2>
      <div class="channel-tabs">
        <button
          v-for="channel in channels"
          :key="channel.id"
          class="channel-tab"
          :class="{ active: activeChannel === channel.id }"
          @click="activeChannel = channel.id"
        >
          {{ channel.icon }} {{ channel.label }}
        </button>
      </div>
    </div>

    <div class="messages-container">
      <div
        v-for="message in filteredMessages"
        :key="message.id"
        class="message-card"
        :class="`message-${message.type}`"
      >
        <div class="message-header">
          <span class="message-sender">{{ getSenderName(message.senderId) }}</span>
          <span v-if="message.receiverId" class="message-receiver">
            → {{ getSenderName(message.receiverId) }}
          </span>
          <span class="message-time">{{ formatTime(message.timestamp) }}</span>
        </div>
        <div class="message-content">{{ message.content }}</div>
      </div>

      <div v-if="filteredMessages.length === 0" class="empty-state">
        <div class="empty-icon">💬</div>
        <div>No messages in this channel yet</div>
      </div>
    </div>

    <!-- Message composition (future feature) -->
    <div class="message-compose">
      <input
        type="text"
        placeholder="Messages are auto-generated by AI agents..."
        disabled
        class="compose-input"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useGameStore } from '@/stores/gameStore'

const gameStore = useGameStore()
const activeChannel = ref<'all' | 'red' | 'blue' | 'enemy'>('all')

const channels = [
  { id: 'all', label: 'All Messages', icon: '📢' },
  { id: 'red', label: 'Red Team', icon: '🔴' },
  { id: 'blue', label: 'Blue Team', icon: '🔵' },
  { id: 'enemy', label: 'Cross-Team', icon: '⚔️' }
]

const filteredMessages = computed(() => {
  const messages = gameStore.recentMessages

  if (activeChannel.value === 'all') {
    return messages
  } else if (activeChannel.value === 'red') {
    return messages.filter(m => m.type === 'team' && isRedCommander(m.senderId))
  } else if (activeChannel.value === 'blue') {
    return messages.filter(m => m.type === 'team' && isBlueCommander(m.senderId))
  } else if (activeChannel.value === 'enemy') {
    return messages.filter(m => m.type === 'enemy')
  }

  return messages
})

function getSenderName(agentId: string): string {
  if (agentId === 'system') return 'System'

  const commander = gameStore.gameState?.commanders.find(c => c.agentId === agentId)
  return commander?.name || agentId
}

function isRedCommander(agentId: string): boolean {
  const commander = gameStore.gameState?.commanders.find(c => c.agentId === agentId)
  return commander?.team === 'red'
}

function isBlueCommander(agentId: string): boolean {
  const commander = gameStore.gameState?.commanders.find(c => c.agentId === agentId)
  return commander?.team === 'blue'
}

function formatTime(timestamp: number): string {
  const date = new Date(timestamp)
  return date.toLocaleTimeString()
}
</script>

<style scoped>
.communication-view {
  display: flex;
  flex-direction: column;
  height: 100%;
  gap: 16px;
}

.view-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 16px;
}

.channel-tabs {
  display: flex;
  gap: 8px;
}

.channel-tab {
  padding: 8px 16px;
  background: var(--color-bg-tertiary);
  border: none;
  border-radius: 6px;
  color: var(--color-text-primary);
  cursor: pointer;
  transition: all 0.2s;
}

.channel-tab:hover {
  background: var(--color-border);
}

.channel-tab.active {
  background: var(--color-blue);
}

.messages-container {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  background: var(--color-bg-tertiary);
  border-radius: 8px;
}

.message-card {
  background: var(--color-bg-secondary);
  padding: 12px;
  margin-bottom: 12px;
  border-radius: 8px;
  border-left: 4px solid;
}

.message-team {
  border-left-color: var(--color-blue);
}

.message-enemy {
  border-left-color: var(--color-warning);
}

.message-system {
  border-left-color: var(--color-success);
  background: rgba(16, 185, 129, 0.1);
}

.message-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
  font-size: 0.85em;
  color: var(--color-text-secondary);
}

.message-sender {
  font-weight: bold;
  color: var(--color-text-primary);
}

.message-receiver {
  color: var(--color-blue);
}

.message-time {
  margin-left: auto;
  font-size: 0.9em;
}

.message-content {
  line-height: 1.5;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: var(--color-text-secondary);
  gap: 16px;
}

.empty-icon {
  font-size: 4em;
  opacity: 0.3;
}

.message-compose {
  padding: 12px;
  background: var(--color-bg-tertiary);
  border-radius: 8px;
}

.compose-input {
  width: 100%;
  padding: 12px;
  background: var(--color-bg-secondary);
  border: 1px solid var(--color-border);
  border-radius: 6px;
  color: var(--color-text-primary);
  font-size: 1em;
}

.compose-input:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
